FROM oven/bun:alpine AS builder
WORKDIR /home/bun/apps/website

COPY apps/website/package.json ./
RUN bun install

COPY apps/website .
RUN bun run build

FROM nginx:alpine
COPY --from=builder /home/bun/apps/website/dist /usr/share/nginx/html
COPY apps/website/.docker/nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]
