FROM oven/bun:alpine AS builder
WORKDIR /home/bun

COPY package.json bun.lock ./
COPY apps/website/package.json apps/website/package.json
RUN bun install --frozen-lockfile --filter @stonkista/website

COPY apps/website apps/website
RUN bun run --cwd apps/website build

FROM nginx:alpine
COPY --from=builder /home/bun/apps/website/dist /usr/share/nginx/html
COPY apps/website/.docker/nginx.conf /etc/nginx/conf.d/default.conf
CMD ["nginx", "-g", "daemon off;"]
