FROM oven/bun:alpine
WORKDIR /home/bun

COPY package.json bun.lock ./
RUN bun install --frozen-lockfile --ignore-scripts

COPY apps/backend apps/backend

CMD ["bun", "--watch", "apps/backend/index.ts"]
