# syntax=docker/dockerfile:1-labs
FROM oven/bun:alpine
WORKDIR /home/bun

COPY package.json bun.lock bunfig.toml ./
COPY --parents ./apps/*/package.json ./

RUN bun install --frozen-lockfile --filter @stonkista/backend

COPY apps/backend apps/backend

WORKDIR /home/bun/apps/backend
CMD ["bun", "--watch", "index.ts"]
